add_test([=[gtest_RB_Tree.InvalidInput]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.InvalidInput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.InvalidInput]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.NullTree]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.NullTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.NullTree]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.EmptyTree]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.EmptyTree]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.EmptyTree]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.ZeroElements]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.ZeroElements]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.ZeroElements]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.EdgeElement]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.EdgeElement]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.EdgeElement]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.SingleInsert]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.SingleInsert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.SingleInsert]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.DuplicateInsert]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.DuplicateInsert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.DuplicateInsert]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.AscendingInsert]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.AscendingInsert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.AscendingInsert]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.DescendingInsert]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.DescendingInsert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.DescendingInsert]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.RandomInsert]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.RandomInsert]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.RandomInsert]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.MixedSignNumbers]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.MixedSignNumbers]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.MixedSignNumbers]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.SubtreeSizeConsistency]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.SubtreeSizeConsistency]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.SubtreeSizeConsistency]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.RangeQuery]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.RangeQuery]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.RangeQuery]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[gtest_RB_Tree.Bounds]=]  /home/vlad/Documents/YLab/03_RangeQuery/google_test [==[--gtest_filter=RB_Tree.Bounds]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[gtest_RB_Tree.Bounds]=]  PROPERTIES WORKING_DIRECTORY /home/vlad/Documents/YLab/03_RangeQuery SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  google_test_TESTS gtest_RB_Tree.InvalidInput gtest_RB_Tree.NullTree gtest_RB_Tree.EmptyTree gtest_RB_Tree.ZeroElements gtest_RB_Tree.EdgeElement gtest_RB_Tree.SingleInsert gtest_RB_Tree.DuplicateInsert gtest_RB_Tree.AscendingInsert gtest_RB_Tree.DescendingInsert gtest_RB_Tree.RandomInsert gtest_RB_Tree.MixedSignNumbers gtest_RB_Tree.SubtreeSizeConsistency gtest_RB_Tree.RangeQuery gtest_RB_Tree.Bounds)
