# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vlad/Documents/YLab/03_RangeQuery

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vlad/Documents/YLab/03_RangeQuery

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vlad/Documents/YLab/03_RangeQuery/CMakeFiles /home/vlad/Documents/YLab/03_RangeQuery//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vlad/Documents/YLab/03_RangeQuery/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tree

# Build rule for target.
tree: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree
.PHONY : tree

# fast build rule for target.
tree/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/build
.PHONY : tree/fast

#=============================================================================
# Target rules for targets named std-set

# Build rule for target.
std-set: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 std-set
.PHONY : std-set

# fast build rule for target.
std-set/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/std-set.dir/build.make CMakeFiles/std-set.dir/build
.PHONY : std-set/fast

#=============================================================================
# Target rules for targets named tree_bench

# Build rule for target.
tree_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tree_bench
.PHONY : tree_bench

# fast build rule for target.
tree_bench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree_bench.dir/build.make CMakeFiles/tree_bench.dir/build
.PHONY : tree_bench/fast

#=============================================================================
# Target rules for targets named set_bench

# Build rule for target.
set_bench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 set_bench
.PHONY : set_bench

# fast build rule for target.
set_bench/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_bench.dir/build.make CMakeFiles/set_bench.dir/build
.PHONY : set_bench/fast

#=============================================================================
# Target rules for targets named google_test

# Build rule for target.
google_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 google_test
.PHONY : google_test

# fast build rule for target.
google_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/google_test.dir/build.make CMakeFiles/google_test.dir/build
.PHONY : google_test/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

src/google_test.o: src/google_test.cpp.o
.PHONY : src/google_test.o

# target to build an object file
src/google_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/google_test.dir/build.make CMakeFiles/google_test.dir/src/google_test.cpp.o
.PHONY : src/google_test.cpp.o

src/google_test.i: src/google_test.cpp.i
.PHONY : src/google_test.i

# target to preprocess a source file
src/google_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/google_test.dir/build.make CMakeFiles/google_test.dir/src/google_test.cpp.i
.PHONY : src/google_test.cpp.i

src/google_test.s: src/google_test.cpp.s
.PHONY : src/google_test.s

# target to generate assembly for a file
src/google_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/google_test.dir/build.make CMakeFiles/google_test.dir/src/google_test.cpp.s
.PHONY : src/google_test.cpp.s

src/std-set.o: src/std-set.cpp.o
.PHONY : src/std-set.o

# target to build an object file
src/std-set.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/std-set.dir/build.make CMakeFiles/std-set.dir/src/std-set.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_bench.dir/build.make CMakeFiles/set_bench.dir/src/std-set.cpp.o
.PHONY : src/std-set.cpp.o

src/std-set.i: src/std-set.cpp.i
.PHONY : src/std-set.i

# target to preprocess a source file
src/std-set.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/std-set.dir/build.make CMakeFiles/std-set.dir/src/std-set.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_bench.dir/build.make CMakeFiles/set_bench.dir/src/std-set.cpp.i
.PHONY : src/std-set.cpp.i

src/std-set.s: src/std-set.cpp.s
.PHONY : src/std-set.s

# target to generate assembly for a file
src/std-set.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/std-set.dir/build.make CMakeFiles/std-set.dir/src/std-set.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/set_bench.dir/build.make CMakeFiles/set_bench.dir/src/std-set.cpp.s
.PHONY : src/std-set.cpp.s

src/tree.o: src/tree.cpp.o
.PHONY : src/tree.o

# target to build an object file
src/tree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/src/tree.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree_bench.dir/build.make CMakeFiles/tree_bench.dir/src/tree.cpp.o
.PHONY : src/tree.cpp.o

src/tree.i: src/tree.cpp.i
.PHONY : src/tree.i

# target to preprocess a source file
src/tree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/src/tree.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree_bench.dir/build.make CMakeFiles/tree_bench.dir/src/tree.cpp.i
.PHONY : src/tree.cpp.i

src/tree.s: src/tree.cpp.s
.PHONY : src/tree.s

# target to generate assembly for a file
src/tree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree.dir/build.make CMakeFiles/tree.dir/src/tree.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tree_bench.dir/build.make CMakeFiles/tree_bench.dir/src/tree.cpp.s
.PHONY : src/tree.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... benchmark"
	@echo "... run_tests"
	@echo "... google_test"
	@echo "... set_bench"
	@echo "... std-set"
	@echo "... tree"
	@echo "... tree_bench"
	@echo "... src/google_test.o"
	@echo "... src/google_test.i"
	@echo "... src/google_test.s"
	@echo "... src/std-set.o"
	@echo "... src/std-set.i"
	@echo "... src/std-set.s"
	@echo "... src/tree.o"
	@echo "... src/tree.i"
	@echo "... src/tree.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

